version: '3'

services:
  api:
    build: .
    container_name: appnodejs
    ports:
      - '5000:80'
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
