version: '3'

services:
  master:
    container_name: 'maestro'
    build: .
    ports:
      - '8089:8089'
    command: '--host=http://8aa5-191-98-182-78.ngrok.io --master'
  slave:
    build: .
    command: '--host=http://8aa5-191-98-182-78.ngrok.io --slave --master-host=maestro'
